### PR TITLE
Whoops, messed up the query params last time!

### PR DESCRIPTION
**Pull request by danmrichards**
## Changes
Fixed query params not being set on request URL.

### CODE REVIEW

**Review by codingconcepts — APPROVED** [review]
I don’t remember seeing from the first PR but was the new query stuff covered by tests?  If not, when you get a chance, would you add a cheeky test for this?

**Comment by danmrichards** [comment]
@codingconcepts: The query key/value stuff was added to the `format` package tests, alongside the existing headers bits

Query - https://github.com/codingconcepts/litmus/blob/master/format/format_test.go#L29
Headers - https://github.com/codingconcepts/litmus/blob/master/format/format_test.go#L32

Currently it'd appear we're just testing the example file can be unmarshaled, encoding it and then throwing it at standard out. So we probably could flesh the tests out a little :thinking:

**Comment by codingconcepts** [comment]
Fixed :)

**Comment by danmrichards** [comment]
Beautiful

**Pull request merged**
